server:
  port: 8085
  servlet:
    context-path: /graduation1 # 该路径需要加载访问地址中，比如：`https://127.0.0.1/graduation1/user/hello2/2`

spring:
  application:
    name: graduation1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gradu_pro?serverTimezone=GMT%2b9
    username: root
    password: 123456

